name: debug-adapter-registry
on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'registry/**'
      - 'schemas/**'
      - 'templates/**'
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    if: |
      ${{ github.event_name == 'pull_request' || github.event_name == 'release' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: 'Check schemas of registry and templates'

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Lint registry and templates
        run: |
          npm ci
          npm run lint

      - name: Check registry schema
        uses: GrantBirki/json-yaml-validate@v5.0.0
        with:
          base_dir: registry
          json_schema: schemas/debug-adapters.schema.json
          yaml_as_json: true
          ajv_strict_mode: false
          use_gitignore: false

      - name: Check templates schemas
        uses: GrantBirki/json-yaml-validate@v5.0.0
        with:
          base_dir: templates
          json_schema: schemas/templates.schema.json
          ajv_strict_mode: false
          use_gitignore: false

  release:
    if: ${{ github.event_name == 'release' }}
    needs: [ tests ]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: ZIP files
        run: zip -r debug-adapter-registry.zip registry schemas templates

      - name: TAR files
        run: tar -czf debug-adapter-registry.tar.gz registry schemas templates

      - name: Attach files to release assets
        id: release_assets
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: debug-adapter-registry.*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
